### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by freiden**
Update dependencies to fix warning due to the release of elixir 1.3 or
modification in the dependent libraries.
There are still warning coming from benchefella since the fix of the
warning has not been released yet.
https://github.com/alco/benchfella/pull/47#issuecomment-239392145

### CODE REVIEW

**Comment by freiden** [comment]
@bryanjos it seems like the build is failing on elixir 1.1.1 and earlier due to the fact that Plug require elixir 1.3. 
How do you want to manage this kind of dependencies problems?

**Comment by bryanjos** [comment]
@freiden so we were having problems with one of our dependencies with 1.0.5 recently. I think with plug also requiring a more recent version of elixir, we should up Joken's version. I think we should take the approach that Elixir took with the Erlang version bump, as well as Plug with it's Elixir version bump requirement and update the minor version on Joken.

Thinking about plug some more, it's also a bit different because it's an optional dependency. I get the idea of the lock file, but I wonder if it matters at all when using Joken or any library as a dependency in an app.

Looking at the Jose bump to 1.8 may be enough of an excuse to bump the minor version and take care of some of these things.

@cs-victor-nascimento what do you think?

**Comment by cs-victor-nascimento** [comment]
I am all for raising the minimum requirements. We just need to raise our
minor version to 3.

Em 13/08/2016 11:13 AM, "Bryan Joseph" <notifications@github.com> escreveu:

**Comment by bryanjos** [comment]
Going to merge this, but also going to update jose and the elixir version as part of #138

**Pull request merged**
