### PR TITLE
Add config option :decode_secret_key? for working with encoded keys.

### PR DESCRIPTION
**Pull request by alanpeabody**
I wasn't sure how to test this effectively, but this does address the encoded secret key issue.

### CODE REVIEW

**Comment by bryanjos** [comment]
Looks good, but is there any documentation or part of the spec you could point me to that shows about decoding the secret key for encoding and decoding? I guess I'm a bit confused and just want to make sure everything is ok.

**Comment by bryanjos** [comment]
Never mind I see what's going on from the demo at jwt.io. I thought the secret came in encoded and was encoded before before used.

**Comment by alanpeabody** [comment]
Honestly, I have found this a bit confusing as well. I don't see anywhere it is explicitly stated. I have done a lot of stumbling around trying to get this working. I have a follow up PR coming that addresses another issues I have stumbled into.

JWT is really cool, and I really appreciate that you have put together an Elixir lib to support it, but I have not found any great JWT resources.

**Comment by bryanjos** [comment]
The spec is what I've been looking at: https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32

No mention of base64 encoded secrets, and it looks like it has been updated a bit. I'll have to look through it again to see what's new

**Pull request merged**
