### PR TITLE
Removed Joken.Helpers

### PR DESCRIPTION
**Pull request by bryanjos**
And added get_current_time to the Joken module #65

### CODE REVIEW

**Comment by cs-victor-nascimento** [comment]
Taking the opportunity we are moving this function and that people will need to refactor existing code, I think we could remove the "get_" part of the function name. So we would end up with `current_time`. This is more in line with timex, erlang and current date/time libraries. Some use `now` but `current_time` seems better as it currently does not clash with names in other libraries.

Other than that, moving it to Joken makes total sense as people will probably import Joken most of the times.

**Comment by bryanjos** [comment]
That's a good point. I will change it

**Comment by cs-victor-nascimento** [comment]
Nice that you liked the idea! This is good!

**Comment by cs-victor-nascimento** [comment]
I guess we can merge this too! What do you think @bryanjos ?

**Comment by bryanjos** [comment]
merged!

**Pull request merged**
