### PR TITLE
Removed warnings found in elixir 1.3. 

### PR DESCRIPTION
**Pull request by bryanjos**
Some refactoring from running credo
#132

### CODE REVIEW

**Comment by cs-victor-nascimento** [comment]
Those changes are all right! The failures in Travis are due to JOSE native dependencies I guess. Maybe we should try and reproduce this first?

**Comment by cs-victor-nascimento** [comment]
It is failing only on Elixir 1.0 in Erlang 17.5. I've refactored the travis config in my fork of the joken but it failed just the same. 

The funny thing is that it actually does not seem to be the native compilation. It complains about some syntax in lib/jose/jwe.ex:339.

Credo is not supporting Elixir 1.0 anymore, so should we raise the bar here? @bryanjos what do you think?

**Comment by bryanjos** [comment]
@cs-victor-nascimento maybe we just remove credo then?

**Comment by bryanjos** [comment]
Now I see what you are talking about @cs-victor-nascimento. Maybe it does make sense to up the Elixir version requirement. Looks like the build breaks only for 1.0.5. 

We could up the Elixir version requirement or I can see about sending a PR to erlang-jose to resolve the error in 1.0.5

**Comment by bryanjos** [comment]
I'm going to merge this and make an issue for the Elixir 1.0 issue

**Pull request merged**
