### PR TITLE
Updated jose to 1.8. Updated elixir version requirement to >= 1.2

### PR DESCRIPTION
**Pull request by bryanjos**
#138

### CODE REVIEW

**Comment by cs-victor-nascimento** [comment]
I guess that is the way the community is dealing with versions. If anyone still use Elixir 1.0 or 1.1 they can still use older versions of Joken.

Just one thing that would be necessary, IMHO, is to have a long-lived branch with Joken 1.2.x series just in case, since this is a somewhat security related library.

**Comment by bryanjos** [comment]
Yeah I think that is a good idea

**Comment by bryanjos** [comment]
Created v1.2 branch based on 1.2.2 https://github.com/bryanjos/joken/tree/v1.2

**Comment by bryanjos** [comment]
With the branch for 1.2 created, I think it is safe to merge this

**Pull request merged**
