### PR TITLE
Added the ability to use a struct for the claims

### PR DESCRIPTION
**Pull request by bryanjos**
Updated the verify functions to take a module parameter to turn the claims into a struct after verification. Added a `with_claims` function to take in a map or struct of claims all at once.

### CODE REVIEW

**Comment by cs-victor-nascimento** [comment]
This is awesome! Anxious to test it on a real project. I think the syntax is awesome. Please merge it!

**Comment by bryanjos** [comment]
Oh I forgot to update this. So I saw José's message on the mailing list to avoid doing a default serialization on structs and so I don't know what the best solution should be. One thing is to only allow maps. The other is to make a protocol that's implemented for the with_claims function. What do you think?

**Comment by bryanjos** [comment]
@cs-victor-nascimento I added a protocol for use when adding claims using `with_claims` that should resolve the issue. I can merge it if you think this will work

**Comment by cs-victor-nascimento** [comment]
I've read José's post on the mailing list. This will work though, if we really want to comply with what he said, we should implement the derive property so that people would not need to implement our protocol all the time. More than that: we should follow Poison's route and provide a `only: [:field1, :field2]` kind of option.

Perhaps we must do that on separated PRs. What do you think?

**Comment by cs-victor-nascimento** [comment]
Besides only, we should prove an exclude option (as I imagine that being more used in our case).

**Pull request merged**
