### PR TITLE
Updated documentation and changelog

### PR DESCRIPTION
**Pull request by bryanjos**
Wanted to go through the docs and update anything before releasing.

### CODE REVIEW

**Comment by cs-victor-nascimento** [comment]
Awesome! This looks great \o/

**Comment by bryanjos** [comment]
Cool! Is there anything else you can think of that we need before making a release?

**Comment by cs-victor-nascimento** [comment]
I think we should release 0.16.0 and make an announcement on the mailing list saying we want feedback and this release is like an RC one before 1.0.0

I think all things are in place now. Next thing I will probably do is add some extra documentation for erlang-jose. We depend on it now so I think we should help with that. Issuing `h JOSE.JWS.sign` brings almost no good information.

**Comment by bryanjos** [comment]
Sounds good! I'll prepare the release now

**Comment by cs-victor-nascimento** [comment]
Awesome!

**Pull request merged**
