### PR TITLE
Plug update proposal to new API

### PR DESCRIPTION
**Pull request by bryanjos**
This is a possible update to the plug implementation with the new API. The main differences being that an `on_verifying/1` is used in place of the `config_module` key. This function is used for the user to do any updates to the token before the plug calls `verify`. `on_error/2` returns a tuple of the connection and the updated message. I updated it that way just in case the user wants to update the connection as well before sending 401.

@cs-victor-nascimento for one of the test, I'm getting "Missing Signature" back because there is an error with the input to JOSE.JWK.verify, but I'm not sure exactly what it is yet.

Let me know what you think

### CODE REVIEW

**Comment by cs-victor-nascimento** [comment]
Nice! I am not sure if I am going to have time today but will look into it as soon as I can.

**Comment by cs-victor-nascimento** [comment]
Okay! I've managed to find out what is going on.

First, the test imports Joken and there is a naming mistake. The function parameter is `payload` but what is being piped is a new Token (token is the same as token() - this is a non intentional name clash). So when verifying it ends up without a signature (because the token is brand new so actually there is no token) and that is why it fails with a "Missing signature". I have added a function head to pattern match on this case and give a proper error message. Also, it may be better to change the message "Missing signature" to something like "Could not verify token" as it would be more general and descriptive.

After that I ended up in another issue: with the custom function you are validating the token generated on the "/generate_token" call. That token does not have a `:sub` claim. So, I added a `with_sub/2` call there too.

I have made these changes locally. Would you like me to push straight to the plug_update branch? I guess we will need to close the other PR because this one already has the changes that were in there right?

One suggestion here is: perhaps we shouldn't pass the token as an argument and provide a `with_compact_token/2`? That way the on_verifying will create a token configuration and we only set the token before verifying. What do you think? 

Also, this made me think we should have a `verify!/1` function to ease pattern matching. That could return token or {:error, message}. I am not sure we will need this use case but it seems to fit the overall Elixir scenario of good practices.

I like the idea here! :+1:

**Comment by bryanjos** [comment]
Ah that makes sense. Yes, you can push the changes to the plug_update branch. I guess I should have started the branch from 0.16.0 instead of the one for the other PR. Yeah, it makes sense to close the other one now. I like your ideas and I think they will fit nicely.

**Comment by cs-victor-nascimento** [comment]
Pushed only the fixes. After this gets merged I will make a separate PR with the proposed changes here.

**Comment by cs-victor-nascimento** [comment]
Build passed \o/

I guess we should merge this :+1:

**Comment by bryanjos** [comment]
merged! I'll get rid of the other PR as well

**Comment by bryanjos** [comment]
nevermind I guess it says merged because this one and that one includes the same commit? Excuse my ignorance, I'm new to working with others in github via PRs, but I'm enjoying the process

**Comment by cs-victor-nascimento** [comment]
I did not know that heheheh. But it is nice :+1:

**Pull request merged**
