### PR TITLE
Check if Plug is loaded before defining Joken.Plug module

### PR DESCRIPTION
**Pull request by stevedomin**
If you're using Joken in a project that doesn't use Plug then it won't
compile.

The only thing I changed in this commit is wrapping the module definition in this statement `if Code.ensure_loaded?(Plug.Conn) do ... end`

### CODE REVIEW

**Comment by bryanjos** [comment]
Thanks! This is definitely needed. One question though. Would using the `@on_load` attribute on the module work the same way? If so that might be a cleaner solution.

**Comment by stevedomin** [comment]
I'm not 100% sure but looking at the code it seems that it's loading the module first and then calling the `on_load` hook. Which in this case is never happening because the compilation fails.

**Comment by cs-victor-nascimento** [comment]
I think @stevedomin is right. Also, his approach is what Eric Meadows says should be used [here](https://groups.google.com/forum/#!topic/elixir-lang-talk/Xe9uXE3uGsY).

I am all for merging this! :+1:

**Comment by bryanjos** [comment]
Cool! Thanks again!

**Pull request merged**
